FROM      python:3.12.9-alpine3.21
WORKDIR   /var/btc
COPY      . /var/btc/
RUN       apk add --no-cache postgresql
RUN       pip3 install --upgrade pip
RUN       pip3 install -r /var/btc/requirements.txt
ENV       TZ                "Etc/UTC"
ENV       PATH              /usr/local/bin:$PATH
ENV       PYTHONPATH        "${PYTONPATH}:/var/btc"
EXPOSE    8080
WORKDIR   /var/btc/btc
CMD       gunicorn -w 4 'app:app' --bind=0.0.0.0
