FROM      python:3.12.9-alpine3.21
WORKDIR   /var/btc
COPY      . /var/btc/
RUN       apk add --no-cache supervisor
RUN       pip3 install --upgrade pip
RUN       pip3 install -r /var/btc/requirements.txt
ENV       TZ                "Etc/UTC"
ENV       PATH              /usr/local/bin:$PATH
ENV       PYTHONPATH        "${PYTONPATH}:/var/btc"
WORKDIR   /var/btc/btc
CMD ["/usr/bin/supervisord", "-c", "/var/btc/btc/supervisord.conf"]
